---
# tasks file for ansible-role-kraken-bot
- name: Create kraken-bot namespace
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ kraken_bot_namespace }}"

- name: Create a cron job for kraken-bot
  k8s:
    state: present
    definition:
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: cron
        namespace: "{{ kraken_bot_namespace }}"
      spec:
        schedule: "{{ kraken_bot_schedule }}"
        jobTemplate:
          spec:
            template:
              spec:
                containers:
                  - name: bot
                    image: ericomeehan/kraken-bot
                    env:
                      - name: KRAKEN_API_TOKEN
                        value: "{{ kraken_api_token }}"
                      - name: KRAKEN_API_SEC
                        value: "{{ kraken_api_sec }}"
                      - name: R_VALUE_TARGET
                        value: "{{ kraken_bot_r_value_target }}"
                      - name: INVESTMENT_COUNT
                        value: "{{ kraken_bot_investment_count }}"
                      - name: INVESTMENT_VOLUME
                        value: "{{ kraken_bot_investment_volume }}"
                    command:
                      - /bin/bash
                      - -c
                      - python3
                      - /usr/local/src/kraken-bot/app.py
                restartPolicy: OnFailure
